apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ninemm-frontend

resources:
  - namespace.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: dex-main
  app.kubernetes.io/part-of: 9mm-exchange

