apiVersion: v1
kind: Secret
metadata:
  name: dex-main-secrets
  namespace: ninemm-frontend
type: Opaque
stringData:
  NEXT_PUBLIC_SNAPSHOT_BASE_URL: "https://hub.snapshot.org"
  NEXT_PUBLIC_EXPLORE_API_ENDPOINT: "https://dex.9mm.pro/api"
  SERVER_REDIS_URL: "redis://default:S0nquFpWA9rRMdqI7rmG1jESBMgMyWaM@redis-13538.c325.us-east-1-4.ec2.cloud.redislabs.com:13538"
  NEXT_PUBLIC_SENTRY_DSN: "https://9b2da63c55645f13b6035e91d06347af@o4510433552891904.ingest.de.sentry.io/4510435212525648"
  SENTRY_AUTH_TOKEN: "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"

