apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ninemm-frontend-dev
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
labels:
  - pairs:
      app.kubernetes.io/name: dex-main
      app.kubernetes.io/part-of: 9mm-exchange
      app.kubernetes.io/environment: dev
    includeSelectors: false
